config/routes.rb
ShoppingList::Application.routes.draw do
  get "home/index"

  root "home#index"

  resources :recipes do
    resources :ingredients
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, dependent: :destroy

  accepts_nested_attributes_for :ingredients, :allow_destroy => true

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.ingredients.create(post_params)

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    @ingredient.destroy

    redirect_to recipe_path(@recipe)
  end

  private
    def post_params
      params.require(:ingredient).permit(:content)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(post_params)
    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(post_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private
    def post_params
      params.require(:recipe).permit(:title, :description, ingredients_attributes: [ :id, :content, :_destroy ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<h1>Recipes</h1>

<p>
  <ul>
    <li>Create a recipe</li>
    <li>Create a shopping list</li>
    <li>Drag and drop recipes into the list, automatically lists ingredients</li>
  </ul>
</p>

<p>
  <%= link_to "Create a recipe!", new_recipe_path, class: "button radius" %>
</p>

app/views/ingredients/_form.html.erb
<div class="row">
  <div class="large-3 large-offset-1 columns"><%= i.label :content, "->" %></div>
  <div class="large-8 columns"><%= i.text_field :content %> <%= i.link_to_remove "delete" %></div>
</div>

app/views/ingredients/_ingredient.html.erb
<li>
  <%= ingredient.content %> |
  <%= link_to 'X', [ingredient.recipe, ingredient],
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Werd", root_path %></a></h1>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <li class="divider"></li>
        <li><%= link_to "Browse Recipes", recipes_path %></li>
        <li class="divider"></li>
        <li><%= link_to "New Recipe", new_recipe_path %></li>
      </ul>
      </section>
  </nav>

  <div class="large-8 small-centered columns">
    <%= yield %>
  </div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= nested_form_for @recipe do |f| %>
    <div id="error_container" class="row">
      <div class="large-11 columns">
        <% if @recipe.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited
                this recipe from being saved:</h2>
              <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
      </div>
    </div>

    <div class="row">
        <div class="large-4 columns"><%= f.label :title %></div>
        <div class="large-8 columns"><%= f.text_field :title %></div>
    </div>
    <div class="row">
        <div class="large-4 columns"><%= f.label :description %></div>
        <div class="large-8 columns"><%= f.text_area :description %></div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <h5>Ingredients</h5>
      </div>
    </div>
    <%= f.fields_for :ingredients do |builder| %>
        <%= render 'ingredients/form', :i => builder %>
    <% end %>
    <%= f.link_to_add "add new ingredient", :ingredients %>

    <p>
    <%= f.submit %>
    </p>
<% end %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.description %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe_path(recipe),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<h1> New Recipe </h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<%= @recipe.title %>

<h3>Ingredients</h3>
<ul>
<%= render @recipe.ingredients %>
</ul>